name: Update Glamorous Counts

on:
  schedule:
    - cron: '30 11 * * *'  # Runs every day at 11:10 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_counts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests  # If needed

      - name: Ensure TSV File Exists
        run: |
          touch usage.tsv  # Create the file if it doesn't exist

      - name: Run Python Script
        run: python glamorous_tracking/get_glamorous_counts.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add usage.tsv
          if ! git diff --cached --quiet; then
            git commit -m "Auto update TSV - $(date +'%Y-%m-%d')"
            git push origin main
          else
            echo "No changes to commit."
          fi
